[project]
name = "CP-2"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = []

[tool.uv.sources]
# bird-feeder = { workspace = true }

[tool.uv.workspace]
members = ["bouncing"]

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"
